import { Link, useLocation, useNavigate } from 'react-router-dom'
import { ArrowLeft, Bell, Search, MapPin, Star, Plus, CheckCircle2, CreditCard } from 'lucide-react'
import { products, categories, branches } from '../../data/mockData'
import { createOrder } from '../../services/prototypeStore'
import { usePrototypeContext } from '../../context/PrototypeContext'
import { NotificationPanel } from '../../components/notifications/NotificationPanel'

const titleMap = { home:'Good food. Better bowls.', search:'Search food', orders:'My orders', profile:'My account', categories:'Categories', cart:'Your cart', checkout:'Checkout', payment:'Payment', 'order-success':'Order confirmed', track:'Track order', notifications:'Notifications' }
export function CustomerPage(){const {pathname}=useLocation();const path=pathname.replace('/customer/','')||'home';if(path.startsWith('product/'))return <Product id={path.split('/')[1]}/>;if(path.startsWith('orders/'))return <OrderDetail id={path.split('/')[1]}/>;if(path.startsWith('track/'))return <Tracking id={path.split('/')[1]}/>;return <Page title={titleMap[path]||'Golden Food Bowl'}>{path==='home'&&<Home/>}{path==='search'&&<SearchPage/>}{path==='categories'&&<Categories/>}{path==='orders'&&<Orders/>}{path==='profile'&&<Profile/>}{path==='cart'&&<Cart/>}{path==='checkout'&&<Checkout/>}{path==='payment'&&<Payment/>}{path==='order-success'&&<Success/>}{path==='notifications'&&<CustomerNotifications/>}</Page>}
function Page({title,children}){return <><header className="route-mobile-header"><Link to="/customer/home"><ArrowLeft/></Link><strong>{title}</strong><Link to="/customer/notifications" aria-label="Notifications"><Bell size={19}/></Link></header><div className="route-mobile-body">{children}</div></>}
function Home(){return <><div className="customer-location"><MapPin/><span>Delivering to <strong>Bengaluru</strong></span></div><section className="route-hero"><span>GOLDEN MOMENTS</span><h1>Good food.<br/><em>Better bowls.</em></h1><p>Freshly made, beautifully delivered.</p><Link to="/customer/categories">Explore Menu</Link></section><Link className="route-search" to="/customer/search"><Search/>Search bowls, meals and more</Link><h2>Browse Categories</h2><div className="route-category-row">{categories.map(c=><Link to="/customer/categories" key={c.id}><span>{c.icon}</span>{c.name}</Link>)}</div><h2>Popular at Bowl</h2><div className="route-products">{products.slice(0,4).map(p=><ProductCard key={p.id} p={p}/>)}</div></>}
function ProductCard({p}){return <article className="route-product"><Link to={`/customer/product/${p.id}`} className="route-food-image">{p.image}</Link><div><span className="route-rating"><Star size={12} fill="currentColor"/> {p.rating}</span><h3>{p.name}</h3><small>{p.portion} • {p.calories} kcal</small><div className="route-price"><strong>₹{p.price}</strong><Link to="/customer/cart"><Plus size={16}/></Link></div></div></article>}
function SearchPage(){return <><div className="route-search active"><Search/><input placeholder="Search bowls, meals and more"/></div><div className="route-products">{products.map(p=><ProductCard key={p.id} p={p}/>)}</div></>}
function Categories(){return <><p>Explore the menu by category.</p><div className="route-category-grid">{categories.map(c=><Link to="/customer/search" key={c.id}><span>{c.icon}</span><strong>{c.name}</strong><small>View menu</small></Link>)}</div></>}
function Product({id}){const p=products.find(x=>String(x.id)===id)||products[0];return <Page title={p.name}><div className="route-detail-image">{p.image}</div><span className="route-pill">Available</span><h1>{p.name}</h1><div className="route-rating"><Star size={14} fill="currentColor"/> {p.rating} rating</div><p>{p.description}</p><div className="route-nutrition"><b>{p.portion}<small>Portion</small></b><b>{p.calories}<small>Calories</small></b><b>{p.ingredients.length}<small>Ingredients</small></b></div><h2>Ingredients</h2><div className="ingredient-chips">{p.ingredients.map(i=><span key={i}>{i}</span>)}</div><Link className="route-primary" to="/customer/cart">Add to Cart • ₹{p.price}</Link></Page>}
function Cart(){return <><div className="route-cart-item"><span>🍲</span><div><strong>Paneer Power Bowl</strong><small>₹249 • Qty 1</small></div><strong>₹249</strong></div><div className="route-summary"><span>Subtotal <b>₹249</b></span><span>Delivery <b>₹40</b></span><span>Taxes <b>₹12</b></span><hr/><span>Total <b>₹301</b></span></div><Link className="route-primary" to="/customer/checkout">Proceed to Checkout</Link></>}
function Checkout(){return <><h2>Order type</h2><div className="route-segment"><button>🚚 Delivery</button><button>🏪 Pickup</button></div><h2>Branch</h2><div className="route-card"><span>🏪</span><span>{branches[0].name}<small>{branches[0].distance}</small></span></div><h2>Delivery address</h2><div className="route-card"><MapPin/><span>Home<small>42, 5th Main Road, Bengaluru</small></span></div><h2>Payment</h2><Link className="route-primary" to="/customer/payment">Continue to Payment</Link></>}
function Payment(){const navigate=useNavigate();const {branches:storeBranches}=usePrototypeContext();const branch=storeBranches[0]||branches[0];const place=()=>{const order=createOrder({items:[{productId:products[0].id,quantity:1}],total:301,type:'Delivery',branch:branch.name,customer:'Priya Sharma',paymentMethod:'UPI',driver:'Rahul Kumar',eta:30});navigate(`/customer/order-success?order=${order.id}`)};return <><div className="route-payment-options">{['UPI','Credit / Debit Card','Net Banking','Digital Wallet'].map(x=><button key={x}>◯　{x}<span>›</span></button>)}</div><button className="route-primary" onClick={place}><CreditCard/> Pay ₹301</button></>}
function Success(){const {orders}=usePrototypeContext();const navigate=useNavigate();const order=orders[0];return <div className="route-success"><CheckCircle2/><h1>Order Confirmed!</h1><p>Your order is now visible to Admin, Support and Delivery.</p><b>#{order?.id||'BWL10301'}</b><button className="route-primary" onClick={()=>navigate(`/customer/track/${order?.id||'BWL10301'}`)}>Track Order</button><Link className="route-secondary" to="/customer/orders">View Orders</Link></div>}
function Orders(){const {orders}=usePrototypeContext();return <>{orders.map(o=><Link className="route-order" to={`/customer/orders/${o.id}`} key={o.id}><span>#{o.id}</span><strong>{o.status.replaceAll('_',' ')}</strong><small>₹{o.total} • {o.type} • {o.branch}</small></Link>)}</>}
function OrderDetail({id}){const {orders}=usePrototypeContext();const o=orders.find(x=>x.id===id)||orders[0];return <><h1>Order #{o?.id}</h1><div className="route-status-list">{['CONFIRMED','PREPARING','READY_FOR_PICKUP','ASSIGNED','PICKED_UP','OUT_FOR_DELIVERY','DELIVERED'].map(s=><span key={s}>{s===o?.status||['CONFIRMED','PREPARING'].includes(s)?'✓':'○'} {s.replaceAll('_',' ')}</span>)}</div><Link className="route-primary" to={`/customer/track/${o?.id}`}>Live Track Order</Link></>}
function Tracking({id}){const {orders}=usePrototypeContext();const o=orders.find(x=>x.id===id)||orders[0];return <><div className="route-map">🛵<span>• • • • •</span>🏠</div><h1>Arriving in {o?.eta||25} min</h1><p>Order #{o?.id} • {o?.status?.replaceAll('_',' ')}</p><div className="route-driver"><span>RK</span><div><strong>{o?.driver||'Rahul Kumar'}</strong><small>Delivery partner</small></div><button>Call</button></div></>}
function Profile(){return <><div className="route-profile"><span>PS</span><div><h2>Priya Sharma</h2><small>priya@example.com</small></div></div>{['My addresses','Saved payments'].map(x=><div className="route-list-row" key={x}>{x}<b>›</b></div>)}<Link className="route-list-row" to="/customer/notifications">Notifications <b>›</b></Link><div className="route-list-row">Help & support <b>›</b></div></>}
function CustomerNotifications(){const {notifications}=usePrototypeContext();return <NotificationPanel notifications={notifications} role="customer"/>}
