import React from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { ArrowLeft, Bell, Search, MapPin, Star, Plus, CheckCircle2, CreditCard, LogOut, Minus, Trash2 } from 'lucide-react'
import { products, categories, branches } from '../../data/mockData'
import { createOrder } from '../../services/prototypeStore'
import { usePrototypeContext } from '../../context/PrototypeContext'
import { NotificationPanel } from '../../components/notifications/NotificationPanel'

const titleMap = { home:'Good food. Better bowls.', search:'Search food', orders:'My orders', profile:'My account', categories:'Categories', cart:'Your cart', checkout:'Checkout', payment:'Payment', 'order-success':'Order confirmed', track:'Track order', notifications:'Notifications' }
const CART_KEY='goldbowl_cart', CHECKOUT_KEY='goldbowl_checkout'
const readCart=()=>{try{return JSON.parse(localStorage.getItem(CART_KEY))||[{productId:products[0].id,quantity:1}]}catch{return[{productId:products[0].id,quantity:1}]}}
const saveCart=items=>localStorage.setItem(CART_KEY,JSON.stringify(items))
const money=v=>`₹${Math.round(v)}`
function FoodImage({src,alt,className=''}){return <img className={className} src={src} alt={alt} loading="lazy"/>}
export function CustomerPage(){const {pathname}=useLocation();const path=pathname.replace('/customer/','')||'home';if(path.startsWith('product/'))return <Product id={path.split('/')[1]}/>;if(path.startsWith('orders/'))return <OrderDetail id={path.split('/')[1]}/>;if(path.startsWith('track/'))return <Tracking id={path.split('/')[1]}/>;return <Page title={titleMap[path]||'Golden Food Bowl'}>{path==='home'&&<Home/>}{path==='search'&&<SearchPage/>}{path==='categories'&&<Categories/>}{path==='orders'&&<Orders/>}{path==='profile'&&<Profile/>}{path==='cart'&&<Cart/>}{path==='checkout'&&<Checkout/>}{path==='payment'&&<Payment/>}{path==='order-success'&&<Success/>}{path==='notifications'&&<CustomerNotifications/>}</Page>}
function Page({title,children}){return <><header className="route-mobile-header"><Link to="/customer/home"><ArrowLeft/></Link><strong>{title}</strong><Link to="/customer/notifications"><Bell size={19}/></Link></header><div className="route-mobile-body">{children}</div></>}
function Home(){return <><div className="customer-location"><MapPin/><span>Delivering to <strong>Bengaluru</strong></span></div><section className="route-hero"><span>GOLDEN MOMENTS</span><h1>Good food.<br/><em>Better bowls.</em></h1><p>Freshly made, beautifully delivered.</p><Link to="/customer/categories">Explore Menu</Link></section><Link className="route-search" to="/customer/search"><Search/>Search bowls, meals and more</Link><h2>Browse Categories</h2><div className="route-category-row">{categories.map(c=><Link to="/customer/categories" key={c.id}><span>{c.icon}</span>{c.name}</Link>)}</div><h2>Popular at Bowl</h2><div className="route-products">{products.slice(0,4).map(p=><ProductCard key={p.id} p={p}/>)}</div></>}
function ProductCard({p}){const add=()=>{const cart=readCart(),existing=cart.find(x=>x.productId===p.id);saveCart(existing?cart.map(x=>x.productId===p.id?{...x,quantity:x.quantity+1}:x):[...cart,{productId:p.id,quantity:1}]);window.location.href='/customer/cart'};return <article className="route-product"><Link to={`/customer/product/${p.id}`} className="route-food-image"><FoodImage src={p.image} alt={p.name}/></Link><div><span className="route-rating"><Star size={12} fill="currentColor"/> {p.rating}</span><h3>{p.name}</h3><small>{p.portion} • {p.calories} kcal</small><div className="route-price"><strong>₹{p.price}</strong><button type="button" onClick={e=>{e.preventDefault();add()}}><Plus size={16}/></button></div></div></article>}
function SearchPage(){return <><div className="route-search active"><Search/><input placeholder="Search bowls, meals and more"/></div><div className="route-products">{products.map(p=><ProductCard key={p.id} p={p}/>)}</div></>}
function Categories(){return <><p>Explore the menu by category.</p><div className="route-category-grid">{categories.map(c=><Link to="/customer/search" key={c.id}><span>{c.icon}</span><strong>{c.name}</strong><small>View menu</small></Link>)}</div></>}
function Product({id}){const p=products.find(x=>String(x.id)===id)||products[0];const add=()=>{const cart=readCart(),existing=cart.find(x=>x.productId===p.id);saveCart(existing?cart.map(x=>x.productId===p.id?{...x,quantity:x.quantity+1}:x):[...cart,{productId:p.id,quantity:1}]);window.location.href='/customer/cart'};return <Page title={p.name}><div className="route-detail-image"><FoodImage src={p.image} alt={p.name}/></div><span className="route-pill">Available</span><h1>{p.name}</h1><div className="route-rating"><Star size={14} fill="currentColor"/> {p.rating} rating</div><p>{p.description}</p><div className="route-nutrition"><b>{p.portion}<small>Portion</small></b><b>{p.calories}<small>Calories</small></b><b>{p.ingredients.length}<small>Ingredients</small></b></div><h2>Ingredients</h2><div className="ingredient-chips">{p.ingredients.map(i=><span key={i}>{i}</span>)}</div><button type="button" className="route-primary" onClick={add}>Add to Cart • ₹{p.price}</button></Page>}
function Cart(){const navigate=useNavigate();const [items,setItems]=React.useState(readCart);const detailed=items.map(i=>({...i,product:products.find(p=>p.id===i.productId)||products[0]}));const update=(id,d)=>{const next=items.map(i=>i.productId===id?{...i,quantity:i.quantity+d}:i).filter(i=>i.quantity>0);setItems(next);saveCart(next)};const subtotal=detailed.reduce((s,i)=>s+i.product.price*i.quantity,0),delivery=subtotal?40:0,taxes=Math.round(subtotal*.05),total=subtotal+delivery+taxes;if(!detailed.length)return <div className="route-success"><h1>Your cart is empty</h1><p>Add a bowl from the menu to continue.</p><Link className="route-primary" to="/customer/categories">Explore Menu</Link></div>;return <><div>{detailed.map(i=><div className="route-cart-item" key={i.productId}><span className="route-cart-image"><FoodImage src={i.product.image} alt={i.product.name}/></span><div><strong>{i.product.name}</strong><small>{money(i.product.price)} • Qty {i.quantity}</small><div style={{display:'flex',gap:6,marginTop:8}}><button type="button" onClick={()=>update(i.productId,-1)}><Minus size={13}/></button><button type="button" onClick={()=>update(i.productId,1)}><Plus size={13}/></button><button type="button" onClick={()=>update(i.productId,-i.quantity)}><Trash2 size={13}/></button></div></div><strong>{money(i.product.price*i.quantity)}</strong></div>)}</div><div className="route-summary"><span>Subtotal <b>{money(subtotal)}</b></span><span>Delivery <b>{money(delivery)}</b></span><span>Taxes <b>{money(taxes)}</b></span><hr/><span>Total <b>{money(total)}</b></span></div><button type="button" className="route-primary" onClick={()=>{localStorage.setItem(CHECKOUT_KEY,JSON.stringify({items,subtotal,delivery,taxes,total}));navigate('/customer/checkout')}}>Proceed to Checkout</button></>}
function Checkout(){const navigate=useNavigate();const [type,setType]=React.useState('Delivery');const [branch,setBranch]=React.useState(branches[0]?.id||1);const [address,setAddress]=React.useState('Home');const [cart]=React.useState(()=>{try{return JSON.parse(localStorage.getItem(CHECKOUT_KEY))||null}catch{return null}});if(!cart)return <div className="route-success"><h1>Your checkout is empty</h1><Link className="route-primary" to="/customer/cart">Back to Cart</Link></div>;const selectedBranch=branches.find(b=>b.id===branch)||branches[0];return <><h2>Order type</h2><div className="route-segment"><button type="button" className={type==='Delivery'?'active':''} onClick={()=>setType('Delivery')}>🚚 Delivery</button><button type="button" className={type==='Pickup'?'active':''} onClick={()=>setType('Pickup')}>🏪 Pickup</button></div><h2>Branch</h2>{branches.map(b=><button type="button" className="route-card" key={b.id} onClick={()=>setBranch(b.id)} style={{width:'100%',textAlign:'left',borderColor:b.id===branch?'#b4811d':undefined}}><span>🏪</span><span>{b.name}<small>{b.distance}</small></span><b>{b.id===branch?'✓':'›'}</b></button>)}{type==='Delivery'&&<><h2>Delivery address</h2><button type="button" className="route-card" onClick={()=>setAddress(address==='Home'?'Work':'Home')} style={{width:'100%',textAlign:'left'}}><MapPin/><span>{address}<small>{address==='Home'?'42, 5th Main Road, Bengaluru':'12, MG Road, Bengaluru'}</small></span><b>Change</b></button></>}<h2>Order total</h2><div className="route-summary"><span>Total <b>{money(cart.total)}</b></span></div><button type="button" className="route-primary" onClick={()=>{localStorage.setItem(CHECKOUT_KEY,JSON.stringify({...cart,type,branch:selectedBranch.id,address}));navigate('/customer/payment')}}>Continue to Payment</button></>}
function Payment(){const navigate=useNavigate();const {branches:storeBranches}=usePrototypeContext();const [method,setMethod]=React.useState('UPI');const cart=(()=>{try{return JSON.parse(localStorage.getItem(CHECKOUT_KEY))||null}catch{return null}})();const branch=(cart?.branch?branches.find(b=>b.id===cart.branch):null)||storeBranches[0]||branches[0];if(!cart)return <div className="route-success"><h1>Checkout expired</h1><Link className="route-primary" to="/customer/cart">Return to Cart</Link></div>;const place=()=>{const order=createOrder({items:cart.items,total:cart.total,type:cart.type||'Delivery',branch:branch?.name||'Golden Food Bowl',customer:'Priya Sharma',paymentMethod:method,driver:cart.type==='Delivery'?'Rahul Kumar':null,eta:cart.type==='Delivery'?30:0});localStorage.removeItem(CART_KEY);localStorage.removeItem(CHECKOUT_KEY);navigate(`/customer/order-success?order=${order.id}`)};return <><div className="route-payment-options">{['UPI','Credit / Debit Card','Net Banking','Digital Wallet'].map(x=><button type="button" key={x} onClick={()=>setMethod(x)} style={{borderColor:method===x?'#b4811d':undefined,background:method===x?'#fff9ec':undefined}}><span>{method===x?'◉':'◯'}　{x}</span><span>›</span></button>)}</div><div className="route-summary"><span>Order total <b>{money(cart.total)}</b></span></div><button type="button" className="route-primary" onClick={place}><CreditCard/> Pay {money(cart.total)}</button></>}
function Success(){const {orders}=usePrototypeContext();const navigate=useNavigate();const id=new URLSearchParams(window.location.search).get('order');const order=orders.find(o=>o.id===id)||orders[0];return <div className="route-success"><CheckCircle2/><h1>Order Confirmed!</h1><p>Your order is now visible to Admin, Support and Delivery.</p><b>#{order?.id||id||'BWL10301'}</b><button type="button" className="route-primary" onClick={()=>navigate(`/customer/track/${order?.id||id||'BWL10301'}`)}>Track Order</button><Link className="route-secondary" to="/customer/orders">View Orders</Link></div>}
function Orders(){const {orders}=usePrototypeContext();return <>{orders.map(o=><Link className="route-order" to={`/customer/orders/${o.id}`} key={o.id}><span>#{o.id}</span><strong>{o.status.replaceAll('_',' ')}</strong><small>₹{o.total} • {o.type} • {o.branch}</small></Link>)}</>}
function OrderDetail({id}){const {orders}=usePrototypeContext();const o=orders.find(x=>x.id===id)||orders[0];return <><h1>Order #{o?.id}</h1><div className="route-status-list">{['CONFIRMED','PREPARING','READY_FOR_PICKUP','ASSIGNED','PICKED_UP','OUT_FOR_DELIVERY','DELIVERED'].map(s=><span key={s}>{s===o?.status||['CONFIRMED','PREPARING'].includes(s)?'✓':'○'} {s.replaceAll('_',' ')}</span>)}</div><Link className="route-primary" to={`/customer/track/${o?.id}`}>Live Track Order</Link></>}
function Tracking({id}){const {orders}=usePrototypeContext();const o=orders.find(x=>x.id===id)||orders[0];return <><div className="route-map">🛵<span>• • • • •</span>🏠</div><h1>Arriving in {o?.eta||25} min</h1><p>Order #{o?.id} • {o?.status?.replaceAll('_',' ')}</p><div className="route-driver"><span>RK</span><div><strong>{o?.driver||'Rahul Kumar'}</strong><small>Delivery partner</small></div><button type="button">Call</button></div></>}
function Profile(){const navigate=useNavigate();const signOut=()=>{sessionStorage.removeItem('bowlCustomerMobile');sessionStorage.removeItem('bowlCustomerEmail');sessionStorage.removeItem('bowlCustomerLocation');navigate('/customer/signin',{replace:true})};return <><div className="route-profile"><span>PS</span><div><h2>Priya Sharma</h2><small>priya@example.com</small></div></div>{['My addresses','Saved payments'].map(x=><div className="route-list-row" key={x}>{x}<b>›</b></div>)}<Link className="route-list-row" to="/customer/notifications">Notifications <b>›</b></Link><div className="route-list-row">Help & support <b>›</b></div><button type="button" className="route-list-row" onClick={signOut}><span><LogOut size={17}/> Sign out</span><b>›</b></button></>}
function CustomerNotifications(){const {notifications}=usePrototypeContext();return <NotificationPanel notifications={notifications} role="customer"/>}
