import { Link, useLocation, useNavigate } from 'react-router-dom'
import { MapPin, PackageCheck, Navigation, Bell, LogOut, UserRound, Mail, Phone, Car, FileText, CreditCard } from 'lucide-react'
import { useState } from 'react'
import { usePrototypeContext } from '../../context/PrototypeContext'
import { updateOrderStatus } from '../../services/prototypeStore'
import { NotificationPanel } from '../../components/notifications/NotificationPanel'

const LOGO='https://res.cloudinary.com/dwmjz9csc/image/upload/v1787120716/image-removebg-preview_e1wfil.png'

export function DeliveryPage(){const {pathname}=useLocation();const navigate=useNavigate();const path=pathname.replace('/delivery/','')||'dashboard';const {orders,notifications}=usePrototypeContext();const assigned=orders.filter(o=>o.driver==='Rahul Kumar'&&o.status!=='DELIVERED');const current=assigned[0]||orders[0];const location=JSON.parse(localStorage.getItem('bowlDeliveryLocation')||'null');const signOut=()=>{localStorage.removeItem('bowlDeliveryOnboarding');localStorage.removeItem('bowlDeliveryLocation');sessionStorage.removeItem('bowlDeliveryAuth');navigate('/delivery/signin',{replace:true})};return <div className="delivery-route"><header><img src={LOGO} alt="Golden Food Bowl"/><strong>Delivery Partner</strong><Link to="/delivery/notifications" aria-label="Notifications"><Bell/></Link></header>{path==='dashboard'&&<><h1>Good afternoon, Rahul</h1><div className="delivery-stat"><strong>{assigned.length}</strong><span>Active orders assigned</span></div><div className="delivery-location-status"><MapPin/><div><strong>{location?.label||'Location not shared yet'}</strong><small>{location?'Current device location • Sharing ready':'Complete location setup to share your delivery area'}</small></div>{!location&&<Link to="/delivery/onboarding-fee">Set location</Link>}</div><h2>Current assignment</h2>{current?<Link className="delivery-order" to={`/delivery/orders/${current.id}`}><PackageCheck/><div><strong>#{current.id}</strong><small>{current.customer} • ₹{current.total}</small><small>{current.branch} → 42, 5th Main Road</small></div><b>›</b></Link>:<p>No active assignments.</p>}</>}{path==='orders'&&<><h1>Assigned Orders</h1>{assigned.length?assigned.map(o=><Link className="delivery-order" to={`/delivery/orders/${o.id}`} key={o.id}><PackageCheck/><div><strong>#{o.id}</strong><small>{o.branch} → customer</small><small>{o.status.replaceAll('_',' ')}</small></div><b>›</b></Link>):<p>No active assignments.</p>}</>}{path.startsWith('orders/')&&<Order id={path.split('/')[1]}/>} {path.startsWith('navigation/')&&<NavigationView id={path.split('/')[1]}/>} {path==='profile'&&<DeliveryProfile/>}{path==='notifications'&&<NotificationPanel notifications={notifications} role="delivery"/>}</div>}

function DeliveryProfile(){const saved=JSON.parse(localStorage.getItem('bowlDeliveryOnboarding')||'{}');const[editing,setEditing]=useState(false);const[data,setData]=useState({name:saved.name||'Rahul Kumar',email:saved.email||'partner@example.com',mobile:saved.mobile||'9876543210',vehicle:saved.vehicle||'Bike',vehicleNumber:saved.vehicleNumber||'KA01AB1234',licence:saved.licence||'DL-XXXX-1234',idProof:saved.idProof||'ID-XXXX',bank:saved.bank||'Account details',upi:saved.upi||'rahul@upi'});const set=(k,v)=>setData(d=>({...d,[k]:v}));const save=()=>{localStorage.setItem('bowlDeliveryOnboarding',JSON.stringify({...saved,...data}));setEditing(false)};return <div className="delivery-profile-page"><div className="delivery-profile-hero"><div className="delivery-avatar">RK</div><div><span className="eyebrow">DELIVERY PARTNER</span><h1>{data.name}</h1><p>Verified partner profile</p></div><button onClick={()=>setEditing(!editing)}>{editing?'Cancel':'Edit'}</button></div><div className="delivery-profile-grid"><ProfileField icon={UserRound} label="Full name" value={data.name} edit={editing} onChange={v=>set('name',v)}/><ProfileField icon={Mail} label="Email" value={data.email} edit={editing} onChange={v=>set('email',v)}/><ProfileField icon={Phone} label="Mobile" value={data.mobile} edit={editing} onChange={v=>set('mobile',v)}/><ProfileField icon={Car} label="Vehicle" value={`${data.vehicle} • ${data.vehicleNumber}`} edit={editing} onChange={v=>set('vehicleNumber',v)}/><ProfileField icon={FileText} label="Driving licence" value={data.licence} edit={editing} onChange={v=>set('licence',v)}/><ProfileField icon={FileText} label="ID proof" value={data.idProof} edit={editing} onChange={v=>set('idProof',v)}/><ProfileField icon={CreditCard} label="Bank details" value={data.bank} edit={editing} onChange={v=>set('bank',v)}/><ProfileField icon={CreditCard} label="UPI ID" value={data.upi} edit={editing} onChange={v=>set('upi',v)}/></div>{editing&&<button className="delivery-save-profile" onClick={save}>Save profile</button>}</div>}
function ProfileField({icon:Icon,label,value,edit,onChange}){return <label className="delivery-profile-field"><Icon/><span>{label}</span>{edit?<input value={value} onChange={e=>onChange(e.target.value)}/>:<strong>{value}</strong>}</label>}
function Order({id}){const {orders}=usePrototypeContext();const order=orders.find(o=>o.id===id);if(!order)return <p>Order not found.</p>;const advance=()=>{const next={ASSIGNED:'PICKED_UP',PICKED_UP:'OUT_FOR_DELIVERY',OUT_FOR_DELIVERY:'DELIVERED'}[order.status];if(next)updateOrderStatus(order.id,next)};return <><h1>Order #{order.id}</h1><div className="delivery-address"><MapPin/><div><strong>Pickup</strong><small>{order.branch}</small></div></div><div className="delivery-address"><Navigation/><div><strong>Drop-off</strong><small>42, 5th Main Road, Bengaluru</small></div></div><div className="delivery-actions">{order.status==='ASSIGNED'&&<button onClick={advance}>Accept & Pick Up</button>}{order.status==='PICKED_UP'&&<button onClick={advance}>Start Delivery</button>}{order.status==='OUT_FOR_DELIVERY'&&<button onClick={advance}>Mark Delivered</button>}<Link to={`/delivery/navigation/${order.id}`}>Start Navigation</Link></div></>}
function NavigationView({id}){const location=JSON.parse(localStorage.getItem('bowlDeliveryLocation')||'null');return <><h1>Navigation</h1><div className="route-map">📍 ───────── 🛵 ───────── 🏠</div><p>{location?`Sharing current location from ${location.label}.`:'Live location sharing is simulated for the prototype.'}</p><Link className="route-primary" to={`/delivery/orders/${id}`}>Back to Order</Link></>}
