import { Link, useLocation } from 'react-router-dom'
import { MapPin, PackageCheck, Navigation, Bell } from 'lucide-react'
import { usePrototypeContext } from '../../context/PrototypeContext'
import { updateOrderStatus } from '../../services/prototypeStore'
import { NotificationPanel } from '../../components/notifications/NotificationPanel'

export function DeliveryPage(){const {pathname}=useLocation();const path=pathname.replace('/delivery/','')||'dashboard';const {orders,notifications}=usePrototypeContext();const assigned=orders.filter(o=>o.driver==='Rahul Kumar'&&o.status!=='DELIVERED');const current=assigned[0]||orders[0];return <div className="delivery-route"><header><span>🥣</span><strong>Delivery Partner</strong><Link to="/delivery/notifications" aria-label="Notifications"><Bell/></Link></header>{path==='dashboard'&&<><h1>Good afternoon, Rahul</h1><div className="delivery-stat"><strong>{assigned.length}</strong><span>Active orders assigned</span></div><h2>Current assignment</h2>{current?<Link className="delivery-order" to={`/delivery/orders/${current.id}`}><PackageCheck/><div><strong>#{current.id}</strong><small>{current.customer} • ₹{current.total}</small><small>{current.branch} → 42, 5th Main Road</small></div><b>›</b></Link>:<p>No active assignments.</p>}</>}{path==='orders'&&<><h1>Assigned Orders</h1>{assigned.length?assigned.map(o=><Link className="delivery-order" to={`/delivery/orders/${o.id}`} key={o.id}><PackageCheck/><div><strong>#{o.id}</strong><small>{o.branch} → customer</small><small>{o.status.replaceAll('_',' ')}</small></div><b>›</b></Link>):<p>No active assignments.</p>}</>}{path.startsWith('orders/')&&<Order id={path.split('/')[1]}/>} {path.startsWith('navigation/')&&<NavigationView id={path.split('/')[1]}/>} {path==='profile'&&<><h1>Profile</h1><div className="delivery-profile"><span>RK</span><div><strong>Rahul Kumar</strong><small>Delivery Partner</small></div></div></>}{path==='notifications'&&<NotificationPanel notifications={notifications} role="delivery"/>}</div>}
function Order({id}){const {orders}=usePrototypeContext();const order=orders.find(o=>o.id===id);if(!order)return <p>Order not found.</p>;const advance=()=>{const next={ASSIGNED:'PICKED_UP',PICKED_UP:'OUT_FOR_DELIVERY',OUT_FOR_DELIVERY:'DELIVERED'}[order.status];if(next)updateOrderStatus(order.id,next)};return <><h1>Order #{order.id}</h1><div className="delivery-address"><MapPin/><div><strong>Pickup</strong><small>{order.branch}</small></div></div><div className="delivery-address"><Navigation/><div><strong>Drop-off</strong><small>42, 5th Main Road, Bengaluru</small></div></div><div className="delivery-actions">{order.status==='ASSIGNED'&&<button onClick={advance}>Accept & Pick Up</button>}{order.status==='PICKED_UP'&&<button onClick={advance}>Start Delivery</button>}{order.status==='OUT_FOR_DELIVERY'&&<button onClick={advance}>Mark Delivered</button>}<Link to={`/delivery/navigation/${order.id}`}>Start Navigation</Link></div></>}
function NavigationView({id}){return <><h1>Navigation</h1><div className="route-map">📍 ───────── 🛵 ───────── 🏠</div><p>Live location sharing is simulated for the prototype.</p><Link className="route-primary" to={`/delivery/orders/${id}`}>Back to Order</Link></>}
