import { useState } from 'react'
import { useLocation } from 'react-router-dom'
import { BarChart3, Package, Store, Users, Truck, CheckCircle2, Plus, ToggleLeft, ToggleRight } from 'lucide-react'
import { usePrototypeContext } from '../../context/PrototypeContext'
import { assignDelivery, updateOrderStatus, duplicateBranch, addProduct, toggleProductAvailability, addCategory, updateDeliveryVerification } from '../../services/prototypeStore'
import { NotificationPanel } from '../../components/notifications/NotificationPanel'

const navTitles={dashboard:'Overview',orders:'Orders',products:'Products',categories:'Categories',branches:'Branches',customers:'Customers',delivery:'Delivery Personnel',support:'Support Team',reports:'Sales & Reports',notifications:'Notifications'}
export function AdminPage(){const {pathname}=useLocation();const path=pathname.replace('/admin/','')||'dashboard';const title=navTitles[path]||'Admin';return <section><div className="dashboard-top"><div><span className="eyebrow">GOLDEN FOOD BOWL</span><h1>{title}</h1></div><button>Admin ▾</button></div>{path==='dashboard'&&<Dashboard/>}{path==='orders'&&<Orders/>}{path==='products'&&<Products/>}{path==='categories'&&<Categories/>}{path==='branches'&&<Branches/>}{path==='customers'&&<Customers/>}{path==='delivery'&&<Delivery/>}{path==='support'&&<Support/>}{path==='reports'&&<Dashboard reports/>}{path==='notifications'&&<AdminNotifications/>}</section>}
function Dashboard(){const {orders}=usePrototypeContext();const sales=orders.reduce((s,o)=>s+Number(o.total||0),0);return <><div className="admin-stats"><div><BarChart3/><strong>₹{sales.toLocaleString('en-IN')}</strong><span>Prototype sales</span></div><div><Package/><strong>{orders.length}</strong><span>Orders</span></div><div><Users/><strong>1,284</strong><span>Customers</span></div><div><Truck/><strong>32</strong><span>Delivery staff</span></div></div><Orders/></>}
function Orders(){const {orders}=usePrototypeContext();return <div className="admin-table-card"><div className="table-heading"><h2>Live Orders</h2><span>{orders.length} orders</span></div><table><thead><tr>{['Order','Branch','Customer','Amount','Status','Actions'].map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><strong>#{o.id}</strong></td><td>{o.branch}</td><td>{o.customer}</td><td>₹{o.total}</td><td><span className="table-status">{o.status.replaceAll('_',' ')}</span></td><td>{o.status!=='DELIVERED'&&<button onClick={()=>o.status==='READY_FOR_PICKUP'?assignDelivery(o.id,'Rahul Kumar'):updateOrderStatus(o.id,nextStatus(o.status))}>{o.status==='READY_FOR_PICKUP'?'Assign delivery':'Advance'}</button>}</td></tr>)}</tbody></table></div>}
const nextStatus=s=>({CONFIRMED:'PREPARING',PREPARING:'READY_FOR_PICKUP',ASSIGNED:'PICKED_UP',PICKED_UP:'OUT_FOR_DELIVERY',OUT_FOR_DELIVERY:'DELIVERED'}[s]||s)
function Products(){const {products}=usePrototypeContext();const [name,setName]=useState('');const [price,setPrice]=useState('');const add=()=>{if(name.trim()&&price)addProduct({name:name.trim(),price:Number(price),category:'bowls',portion:'1 bowl',calories:450,image:'🍲'});setName('');setPrice('')};return <div className="admin-table-card"><div className="table-heading"><h2>Products</h2><div><input placeholder="Product name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Price" type="number" value={price} onChange={e=>setPrice(e.target.value)}/><button onClick={add}><Plus/> Add</button></div></div><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Availability</th><th>Actions</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.category}</td><td>₹{p.price}</td><td>{p.available!==false?'Available':'Unavailable'}</td><td><button onClick={()=>toggleProductAvailability(p.id)}>{p.available!==false?<ToggleRight/>:<ToggleLeft/>}</button></td></tr>)}</tbody></table></div>}
function Categories(){const {categories}=usePrototypeContext();const [name,setName]=useState('');const add=()=>{if(name.trim())addCategory({name:name.trim(),icon:'🍲'});setName('')};return <div className="admin-table-card"><div className="table-heading"><h2>Categories</h2><div><input placeholder="Category name" value={name} onChange={e=>setName(e.target.value)}/><button onClick={add}><Plus/> Add</button></div></div><table><thead><tr><th>Category</th><th>Products</th><th>Status</th></tr></thead><tbody>{categories.map(c=><tr key={c.id}><td><strong>{c.icon} {c.name}</strong></td><td>Menu items</td><td><span className="table-status">Active</span></td></tr>)}</tbody></table></div>}
function Customers(){const {users}=usePrototypeContext();return <div className="admin-table-card"><div className="table-heading"><h2>Customers</h2><span>{users.length} prototype accounts</span></div><table><thead><tr><th>Name</th><th>Mobile</th><th>Email</th><th>Provider</th><th>Status</th></tr></thead><tbody>{users.length?users.map(u=><tr key={u.id}><td><strong>{u.name}</strong></td><td>{u.mobile}</td><td>{u.email||'—'}</td><td>{u.provider}</td><td><span className="table-status">Active</span></td></tr>):<tr><td colSpan="5">No customer signups yet. Use the customer signup flow to create a demo account.</td></tr>}</tbody></table></div>}
function Delivery(){const {deliveryPartners}=usePrototypeContext();return <div className="admin-table-card"><div className="table-heading"><h2>Delivery Partner Verification</h2><span>{deliveryPartners.length} applications</span></div><table><thead><tr><th>Partner</th><th>Mobile</th><th>Vehicle</th><th>Documents</th><th>Fee</th><th>Verification</th></tr></thead><tbody>{deliveryPartners.length?deliveryPartners.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.mobile}</td><td>{p.vehicle}</td><td>{p.documentsVerified?'Verified':'Pending'}</td><td>₹{p.fee} • {p.feeStatus}</td><td><button onClick={()=>updateDeliveryVerification(p.id,'VERIFIED','PAID')}>{p.verificationStatus==='VERIFIED'?<CheckCircle2/>:'Verify partner'}</button></td></tr>):<tr><td colSpan="6">No partner applications yet.</td></tr>}</tbody></table></div>}
function Support(){return <div className="admin-table-card"><div className="table-heading"><h2>Support Team</h2><span>Role oversight</span></div><table><thead><tr><th>Agent</th><th>Open Cases</th><th>Resolved</th><th>Status</th></tr></thead><tbody>{['Ananya Rao','Vikram Shah','Meera Das'].map((name,i)=><tr key={name}><td><strong>{name}</strong></td><td>{3-i}</td><td>{18+i*4}</td><td><span className="table-status">Active</span></td></tr>)}</tbody></table></div>}
function Branches(){const {branches}=usePrototypeContext();const [message,setMessage]=useState('');return <div className="branch-admin-grid">{branches.map(b=><article key={b.id}><Store/><h2>{b.name}</h2><p>Bengaluru • {b.distance}</p><div><button>Edit</button><button onClick={()=>{duplicateBranch(b.id,{name:`${b.name} Express`,distance:'2.0 km'});setMessage(`Menu duplicated from ${b.name}`)}}>Duplicate Menu</button></div></article>)}{message&&<p><CheckCircle2/> {message}</p>}</div>}
function AdminNotifications(){const {notifications}=usePrototypeContext();return <NotificationPanel notifications={notifications} role="admin"/>}
