import { useState } from 'react'
import { useLocation } from 'react-router-dom'
import { BarChart3, Package, Store, Users, Truck, CheckCircle2 } from 'lucide-react'
import { usePrototypeContext } from '../../context/PrototypeContext'
import { assignDelivery, updateOrderStatus, duplicateBranch } from '../../services/prototypeStore'
import { NotificationPanel } from '../../components/notifications/NotificationPanel'

const navTitles={dashboard:'Overview',orders:'Orders',products:'Products',categories:'Categories',branches:'Branches',customers:'Customers',delivery:'Delivery Personnel',support:'Support Team',reports:'Sales & Reports',notifications:'Notifications'}
export function AdminPage(){const {pathname}=useLocation();const path=pathname.replace('/admin/','')||'dashboard';const title=navTitles[path]||'Admin';return <section><div className="dashboard-top"><div><span className="eyebrow">GOLDEN FOOD BOWL</span><h1>{title}</h1></div><button>Admin ▾</button></div>{path==='dashboard'&&<Dashboard/>}{path==='orders'&&<Orders/>}{path==='products'&&<Table title="Products" columns={['Product','Category','Price','Availability','Actions']}/>} {path==='categories'&&<Table title="Categories" columns={['Category','Products','Status','Actions']}/>} {path==='branches'&&<Branches/>}{path==='customers'&&<Table title="Customers" columns={['Customer','Orders','Spend','Status','Actions']}/>} {path==='delivery'&&<Table title="Delivery Personnel" columns={['Partner','Orders','Active','Rating','Status']}/>} {path==='support'&&<Table title="Support Team" columns={['Agent','Open Cases','Resolved','Status']}/>} {path==='reports'&&<Dashboard reports/>}{path==='notifications'&&<AdminNotifications/>}</section>}
function Dashboard(){const {orders}=usePrototypeContext();const sales=orders.reduce((s,o)=>s+Number(o.total||0),0);return <><div className="admin-stats"><div><BarChart3/><strong>₹{sales.toLocaleString('en-IN')}</strong><span>Prototype sales</span></div><div><Package/><strong>{orders.length}</strong><span>Orders</span></div><div><Users/><strong>1,284</strong><span>Customers</span></div><div><Truck/><strong>32</strong><span>Delivery staff</span></div></div><Orders/></>}
function Orders(){const {orders}=usePrototypeContext();return <div className="admin-table-card"><div className="table-heading"><h2>Live Orders</h2><span>{orders.length} orders</span></div><table><thead><tr>{['Order','Branch','Customer','Amount','Status','Actions'].map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><strong>#{o.id}</strong></td><td>{o.branch}</td><td>{o.customer}</td><td>₹{o.total}</td><td><span className="table-status">{o.status.replaceAll('_',' ')}</span></td><td><button onClick={()=>o.status==='READY_FOR_PICKUP'?assignDelivery(o.id,'Rahul Kumar'):updateOrderStatus(o.id,nextStatus(o.status))}>{o.status==='READY_FOR_PICKUP'?'Assign delivery':'Advance'}</button></td></tr>)}</tbody></table></div>}
const nextStatus=s=>({CONFIRMED:'PREPARING',PREPARING:'READY_FOR_PICKUP',ASSIGNED:'PICKED_UP',PICKED_UP:'OUT_FOR_DELIVERY',OUT_FOR_DELIVERY:'DELIVERED'}[s]||s)
function AdminNotifications(){const {notifications}=usePrototypeContext();return <NotificationPanel notifications={notifications} role="admin"/>}
function Table({title,columns}){return <div className="admin-table-card"><div className="table-heading"><h2>{title}</h2><button>+ Add</button></div><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{[1,2,3,4].map(i=><tr key={i}>{columns.map((c,j)=><td key={c}>{j===0?<strong>#{10300+i}</strong>:j===columns.length-1?<span className="table-status">Active</span>:j===3?'₹1,249':'Golden Food Bowl'}</td>)}</tr>)}</tbody></table></div>}
function Branches(){const {branches}=usePrototypeContext();const [message,setMessage]=useState('');return <div className="branch-admin-grid">{branches.map((b)=><article key={b.id}><Store/><h2>{b.name}</h2><p>Bengaluru • {b.distance}</p><div><button>Edit</button><button onClick={()=>{duplicateBranch(b.id,{name:`${b.name} Express`,distance:'2.0 km'});setMessage(`Menu duplicated from ${b.name}`)}}>Duplicate Menu</button></div></article>)}{message&&<p><CheckCircle2/> {message}</p>}</div>}
