import { useState } from 'react'
import { useLocation } from 'react-router-dom'
import { Package, Boxes, Headphones, BarChart3, Plus, ToggleLeft, ToggleRight, CheckCircle2 } from 'lucide-react'
import { usePrototypeContext } from '../../context/PrototypeContext'
import { updateOrderStatus, addProduct, toggleProductAvailability, addIssue, updateIssue } from '../../services/prototypeStore'
import { NotificationPanel } from '../../components/notifications/NotificationPanel'

const nextStatus={CONFIRMED:'PREPARING',PREPARING:'READY_FOR_PICKUP',READY_FOR_PICKUP:'ASSIGNED'}
export function SupportPageV3(){const {pathname}=useLocation();const path=pathname.replace('/support/','')||'dashboard';const state=usePrototypeContext();const title={dashboard:'Support Overview',orders:'Incoming Orders',products:'Product Management',issues:'Customer Issues',notifications:'Notifications'}[path]||'Support';return <section><div className="dashboard-top"><div><span className="eyebrow">GOLDEN FOOD BOWL</span><h1>{title}</h1></div><button>Support Agent ▾</button></div>{path==='dashboard'&&<Dashboard state={state}/>} {path==='products'&&<Products products={state.products}/>} {path==='orders'&&<Orders orders={state.orders}/>} {path==='issues'&&<Issues issues={state.issues} orders={state.orders}/>} {path==='notifications'&&<NotificationPanel notifications={state.notifications} role="support"/>}</section>}
function Dashboard({state}){const open=state.orders.filter(o=>o.status!=='DELIVERED').length;return <><div className="admin-stats"><div><Package/><strong>{open}</strong><span>Open orders</span></div><div><Boxes/><strong>{state.products.length}</strong><span>Products</span></div><div><Headphones/><strong>{state.issues.filter(i=>i.status!=='RESOLVED').length}</strong><span>Open issues</span></div><div><BarChart3/><strong>94%</strong><span>Resolved today</span></div></div><Orders orders={state.orders.slice(0,6)}/></>}
function Orders({orders}){return <div className="admin-table-card"><div className="table-heading"><h2>Orders Requiring Attention</h2><span>{orders.length} orders</span></div><table><thead><tr><th>Order</th><th>Customer</th><th>Branch</th><th>Status</th><th>Action</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><strong>#{o.id}</strong></td><td>{o.customer}</td><td>{o.branch}</td><td><span className="table-status">{o.status.replaceAll('_',' ')}</span></td><td>{nextStatus[o.status]?<button onClick={()=>updateOrderStatus(o.id,nextStatus[o.status])}>Update</button>:<span>Monitoring</span>}</td></tr>)}</tbody></table></div>}
function Products({products}){const [name,setName]=useState('');const [price,setPrice]=useState('');const add=()=>{if(name.trim()&&price){addProduct({name:name.trim(),price:Number(price),category:'bowls',portion:'1 bowl',calories:450,image:'🍲'});setName('');setPrice('')}};return <div className="admin-table-card"><div className="table-heading"><h2>Menu Products</h2><div><input placeholder="Product name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Price" type="number" value={price} onChange={e=>setPrice(e.target.value)}/><button onClick={add}><Plus/> Add</button></div></div><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Availability</th><th>Action</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.category}</td><td>₹{p.price}</td><td>{p.available===false?'Unavailable':'Available'}</td><td><button onClick={()=>toggleProductAvailability(p.id)}>{p.available===false?<ToggleLeft/>:<ToggleRight/>}</button></td></tr>)}</tbody></table></div>}
function Issues({issues,orders}){const rows=issues.length?issues:orders.slice(0,4).map((o,i)=>({id:o.id,customer:o.customer,subject:i%2?'Delivery update requested':'Order status enquiry',priority:i===0?'High':'Normal',status:'OPEN'}));const create=()=>{const o=orders[0];if(o)addIssue({orderId:o.id,customer:o.customer,subject:'Customer requested order assistance',priority:'Normal'})};return <div className="admin-table-card"><div className="table-heading"><h2>Customer Issues</h2><button onClick={create}><Plus/> Create issue</button></div><table><thead><tr><th>Reference</th><th>Customer</th><th>Issue</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(i=><tr key={i.id}><td><strong>#{i.id}</strong></td><td>{i.customer}</td><td>{i.subject}</td><td>{i.priority}</td><td><span className="table-status">{i.status}</span></td><td>{i.status!=='RESOLVED'&&issues.some(x=>x.id===i.id)?<button onClick={()=>updateIssue(i.id,'RESOLVED')}><CheckCircle2/> Resolve</button>:<span>Monitoring</span>}</td></tr>)}</tbody></table></div>}
