import { Link, useNavigate } from 'react-router-dom'
import { ArrowLeft, Mail, Phone, UserRound, ShieldCheck, CreditCard, Camera, Car, FileText, Landmark } from 'lucide-react'
import { useState } from 'react'
import { registerCustomer, registerDeliveryPartner } from '../../services/prototypeStore'

const Frame = ({ eyebrow, title, children, back='/' }) => <main className="auth-screen"><div className="auth-card"><Link to={back} className="auth-back"><ArrowLeft/> Back</Link><div className="auth-brand">🥣<span>GOLDEN FOOD BOWL</span></div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{children}</div></main>
const GoogleButton = ({ onClick }) => <button type="button" className="auth-social" onClick={onClick}><b>G</b> Continue with Google</button>
const TextField = ({ icon: Icon, label, ...props }) => <label>{Icon && <Icon/>}{label}<input {...props}/></label>

export function CustomerSignUpPage(){const n=useNavigate();const[name,setName]=useState(''),[mobile,setMobile]=useState(''),[email,setEmail]=useState('');const ok=name.trim()&&/^\d{10}$/.test(mobile);const submit=e=>{e.preventDefault();if(!ok)return;registerCustomer({name:name.trim(),mobile,email});sessionStorage.setItem('bowlCustomerMobile',mobile);sessionStorage.setItem('bowlCustomerEmail',email);n('/customer/verify-otp')};return <Frame eyebrow="CUSTOMER SIGN UP" title="Create your Bowl account"><p>Use your name and mobile number to get started. Email is optional.</p><form onSubmit={submit}><TextField icon={UserRound} label="Full name" value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your name" required/><TextField icon={Phone} label="Mobile number" value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="10-digit mobile number" inputMode="numeric" required/><TextField icon={Mail} label={<>Email <small>optional</small></>} value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" type="email"/><button className="auth-primary" disabled={!ok}>Create account & continue</button></form><p className="auth-switch-text">Already have an account? <Link to="/customer/signin">Sign in</Link></p></Frame>}

export function CustomerSignInPage(){const n=useNavigate();const[mobile,setMobile]=useState(''),[email,setEmail]=useState(''),[otpMode,setOtpMode]=useState(false);const ok=/^\d{10}$/.test(mobile);return <Frame eyebrow="CUSTOMER SIGN IN" title="Welcome back"><p>{otpMode?'Enter the simulated OTP to continue.':'Sign in with mobile OTP, Google, or Email.'}</p>{otpMode?<><TextField icon={Phone} label="Verification code" value={email} onChange={e=>setEmail(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="123456" inputMode="numeric"/><button className="auth-primary" disabled={email.length!==6} onClick={()=>n('/customer/location')}>Verify & continue</button><p className="auth-switch-text">Prototype OTP: <strong>123456</strong></p></>:<><TextField icon={Phone} label="Mobile number" value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="10-digit mobile number" inputMode="numeric"/><button className="auth-primary" disabled={!ok} onClick={()=>{sessionStorage.setItem('bowlCustomerMobile',mobile);setOtpMode(true)}}>Send OTP</button><div className="auth-divider"><span>or continue with</span></div><GoogleButton onClick={()=>n('/customer/location')}/><button type="button" className="auth-social" onClick={()=>n('/customer/location')}><Mail/> Continue with Email</button></>}<p className="auth-switch-text"><Link to="/customer/forgot-password">Forgot mobile access?</Link></p><p className="auth-switch-text">New to Bowl? <Link to="/customer/signup">Create an account</Link></p></Frame>}

export function CustomerVerifyOtpPage(){const n=useNavigate();const[otp,setOtp]=useState('');const mobile=sessionStorage.getItem('bowlCustomerMobile')||'your mobile number';return <Frame eyebrow="OTP VERIFICATION" title="Verify your mobile"><p>Enter the 6-digit code sent to <strong>{mobile}</strong>. Prototype OTP: <strong>123456</strong>.</p><TextField icon={Phone} label="Verification code" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="123456" inputMode="numeric"/><button className="auth-primary" disabled={otp.length!==6} onClick={()=>n('/customer/location')}>Verify & continue</button><p className="auth-switch-text"><Link to="/customer/signin">Use another number</Link></p></Frame>}

export function CustomerForgotPasswordPage(){const n=useNavigate();const[mobile,setMobile]=useState('');return <Frame eyebrow="ACCOUNT RECOVERY" title="Recover your account"><p>Enter your registered mobile number and we'll send a verification code.</p><TextField icon={Phone} label="Mobile number" value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="10-digit mobile number" inputMode="numeric"/><button className="auth-primary" disabled={!/^\d{10}$/.test(mobile)} onClick={()=>{sessionStorage.setItem('bowlCustomerMobile',mobile);n('/customer/verify-otp')}}>Send recovery OTP</button><p className="auth-switch-text"><Link to="/customer/signin">Back to sign in</Link></p></Frame>}

export function DeliverySignUpPage(){const n=useNavigate();const[form,setForm]=useState({name:'',mobile:'',email:'',photo:'',vehicle:'Bike',vehicleNumber:'',licence:'',idProof:'',bank:'',upi:''});const set=(key,value)=>setForm(f=>({...f,[key]:value}));const ok=form.name.trim()&&/^\d{10}$/.test(form.mobile)&&form.email&&form.photo&&form.vehicleNumber&&form.licence&&form.idProof&&form.bank&&form.upi;return <Frame eyebrow="DELIVERY PARTNER SIGN UP" title="Become a Bowl delivery partner"><p>Enter the requested details for the prototype partner profile. No real KYC validation is performed.</p><form onSubmit={e=>{e.preventDefault();if(!ok)return;localStorage.setItem('bowlDeliveryOnboarding',JSON.stringify(form));n('/delivery/verification')}}><TextField icon={UserRound} label="Full name" value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Your full name" required/><TextField icon={Phone} label="Mobile number" value={form.mobile} onChange={e=>set('mobile',e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="10-digit mobile number" inputMode="numeric" required/><TextField icon={Mail} label="Email" value={form.email} onChange={e=>set('email',e.target.value)} placeholder="partner@example.com" type="email" required/><TextField icon={Camera} label="Profile photo" value={form.photo} onChange={e=>set('photo',e.target.value)} placeholder="Photo file / filename" required/><label><Car/>Vehicle type<select value={form.vehicle} onChange={e=>set('vehicle',e.target.value)}><option>Bike</option><option>Scooter</option><option>Car</option></select></label><TextField icon={Car} label="Vehicle number" value={form.vehicleNumber} onChange={e=>set('vehicleNumber',e.target.value)} placeholder="KA01AB1234" required/><TextField icon={FileText} label="Driving licence" value={form.licence} onChange={e=>set('licence',e.target.value)} placeholder="Licence number / document" required/><TextField icon={FileText} label="Aadhaar / ID proof" value={form.idProof} onChange={e=>set('idProof',e.target.value)} placeholder="ID number / document" required/><TextField icon={Landmark} label="Bank account details" value={form.bank} onChange={e=>set('bank',e.target.value)} placeholder="Account / IFSC details" required/><TextField icon={CreditCard} label="UPI ID" value={form.upi} onChange={e=>set('upi',e.target.value)} placeholder="name@upi" required/><button className="auth-primary" disabled={!ok}>Continue to verification</button></form><p className="auth-switch-text">Already a partner? <Link to="/delivery/signin">Sign in</Link></p></Frame>}

export function DeliverySignInPage(){const n=useNavigate();const[mobile,setMobile]=useState(''),[otp,setOtp]=useState(''),[sent,setSent]=useState(false);const ok=/^\d{10}$/.test(mobile);return <Frame eyebrow="DELIVERY PARTNER SIGN IN" title="Welcome back, partner"><p>{sent?'Enter the simulated OTP to continue.':'Sign in with your registered mobile number.'}</p>{!sent?<><TextField icon={Phone} label="Mobile number" value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="10-digit mobile number" inputMode="numeric"/><button className="auth-primary" disabled={!ok} onClick={()=>setSent(true)}>Send OTP</button></>:<><TextField icon={Phone} label="Verification code" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="123456" inputMode="numeric"/><button className="auth-primary" disabled={otp.length!==6} onClick={()=>n('/delivery/dashboard')}>Verify & continue</button><p className="auth-switch-text">Prototype OTP: <strong>123456</strong></p></>}<p className="auth-switch-text">New partner? <Link to="/delivery/signup">Create a partner account</Link></p></Frame>}

export function DeliveryVerificationPage(){const n=useNavigate();const[data,setData]=useState(()=>JSON.parse(localStorage.getItem('bowlDeliveryOnboarding')||'{}'));const[docs,setDocs]=useState(false);const required=['photo','vehicleNumber','licence','idProof','bank','upi'];const complete=required.every(k=>data[k]);return <Frame eyebrow="PARTNER VERIFICATION" title="Review your profile"><p>Prototype document verification checks that the requested inputs are present. Real KYC validation is not performed.</p><div className="auth-summary"><span>Partner <b>{data.name||'New partner'}</b></span><span>Vehicle <b>{data.vehicle||'Bike'} · {data.vehicleNumber||'Not entered'}</b></span><span>Documents <b>{complete?'All details entered':'Missing details'}</b></span></div><label className="auth-check"><input type="checkbox" checked={docs} onChange={e=>setDocs(e.target.checked)}/> I confirm the prototype document fields are submitted</label><button className="auth-primary" disabled={!complete||!docs} onClick={()=>{const next={...data,documentsVerified:true};localStorage.setItem('bowlDeliveryOnboarding',JSON.stringify(next));setData(next);n('/delivery/onboarding-fee')}}>Continue to fee</button></Frame>}

export function DeliveryFeePage(){const n=useNavigate();const[data,setData]=useState(()=>JSON.parse(localStorage.getItem('bowlDeliveryOnboarding')||'{}'));const[paid,setPaid]=useState(false);return <Frame eyebrow="ONBOARDING FEE" title="Complete partner onboarding"><div className="fee-card"><CreditCard/><div><strong>₹499</strong><span>One-time onboarding fee</span></div></div><p>Payment is simulated for this frontend prototype. No real charge is made.</p><button type="button" className="auth-social" onClick={()=>setPaid(true)}>{paid?'✓ Fee marked paid':'Pay ₹499'}</button><button className="auth-primary" disabled={!paid} onClick={()=>{const next={...data,feeStatus:'PAID',verificationStatus:'VERIFIED'};localStorage.setItem('bowlDeliveryOnboarding',JSON.stringify(next));registerDeliveryPartner(next);n('/delivery/application-submitted')}}>Submit application</button></Frame>}

export function DeliveryApplicationSubmittedPage(){return <Frame eyebrow="APPLICATION SUBMITTED" title="You're ready to deliver"><ShieldCheck className="auth-success"/><p>Your prototype partner application is complete. No admin approval is required for this prototype, so you can continue to the delivery dashboard.</p><div className="auth-summary"><span>Documents <b>Submitted</b></span><span>Onboarding fee <b>Paid ₹499</b></span><span>Status <b>Ready</b></span></div><Link className="auth-primary" to="/delivery/dashboard">Go to delivery dashboard</Link></Frame>}
