import { Link, useNavigate } from 'react-router-dom'
import { ArrowLeft, Mail, Phone, UserRound, ShieldCheck, CreditCard } from 'lucide-react'
import { useState } from 'react'
import { registerCustomer, registerDeliveryPartner } from '../../services/prototypeStore'

const Frame = ({ eyebrow, title, children, back='/' }) => <main className="auth-screen"><div className="auth-card"><Link to={back} className="auth-back"><ArrowLeft/> Back</Link><div className="auth-brand">🥣<span>GOLDEN FOOD BOWL</span></div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{children}</div></main>
const GoogleButton = ({ onClick }) => <button type="button" className="auth-social" onClick={onClick}><b>G</b> Continue with Google</button>

export function CustomerSignUpPage(){const n=useNavigate();const[name,setName]=useState(''),[mobile,setMobile]=useState(''),[email,setEmail]=useState('');const ok=name.trim()&&/^\d{10}$/.test(mobile);const submit=e=>{e.preventDefault();if(!ok)return;registerCustomer({name:name.trim(),mobile,email});sessionStorage.setItem('bowlCustomerMobile',mobile);n('/customer/verify-otp')};return <Frame eyebrow="CUSTOMER SIGN UP" title="Create your Bowl account"><p>Use your name and mobile number to get started.</p><form onSubmit={submit}><label><UserRound/>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your name" required/></label><label><Phone/>Mobile number<input value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="10-digit mobile number" inputMode="numeric" required/></label><label><Mail/>Email <small>optional</small><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" type="email"/></label><button className="auth-primary" disabled={!ok}>Create account & continue</button></form><p className="auth-switch-text">Already have an account? <Link to="/customer/signin">Sign in</Link></p></Frame>}

export function CustomerSignInPage(){const n=useNavigate();const[mobile,setMobile]=useState('');const ok=/^\d{10}$/.test(mobile);return <Frame eyebrow="CUSTOMER SIGN IN" title="Welcome back"><p>Sign in with your mobile number or continue with a provider.</p><label><Phone/>Mobile number<input value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="10-digit mobile number" inputMode="numeric"/></label><button className="auth-primary" disabled={!ok} onClick={()=>{sessionStorage.setItem('bowlCustomerMobile',mobile);n('/customer/verify-otp')}}>Send OTP</button><div className="auth-divider"><span>or continue with</span></div><GoogleButton onClick={()=>n('/customer/home')}/><button className="auth-social" onClick={()=>n('/customer/home')}><Mail/> Continue with Email</button><p className="auth-switch-text"><Link to="/customer/forgot-password">Forgot mobile access?</Link></p><p className="auth-switch-text">New to Bowl? <Link to="/customer/signup">Create an account</Link></p></Frame>}

export function CustomerVerifyOtpPage(){const n=useNavigate();const[otp,setOtp]=useState('');const mobile=sessionStorage.getItem('bowlCustomerMobile')||'your mobile number';return <Frame eyebrow="OTP VERIFICATION" title="Verify your mobile"><p>Enter the 6-digit code sent to <strong>{mobile}</strong>. Prototype OTP: <strong>123456</strong>.</p><label><Phone/>Verification code<input value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="123456" inputMode="numeric"/></label><button className="auth-primary" disabled={otp.length!==6} onClick={()=>n('/customer/home')}>Verify & continue</button><p className="auth-switch-text"><Link to="/customer/signin">Use another number</Link></p></Frame>}

export function CustomerForgotPasswordPage(){const n=useNavigate();const[mobile,setMobile]=useState('');return <Frame eyebrow="ACCOUNT RECOVERY" title="Recover your account"><p>Enter your registered mobile number and we'll send a verification code.</p><label><Phone/>Mobile number<input value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="10-digit mobile number" inputMode="numeric"/></label><button className="auth-primary" disabled={!/^\d{10}$/.test(mobile)} onClick={()=>{sessionStorage.setItem('bowlCustomerMobile',mobile);n('/customer/verify-otp')}}>Send recovery OTP</button><p className="auth-switch-text"><Link to="/customer/signin">Back to sign in</Link></p></Frame>}

export function DeliverySignUpPage(){const n=useNavigate();const[name,setName]=useState(''),[mobile,setMobile]=useState(''),[vehicle,setVehicle]=useState('Bike');const ok=name.trim()&&/^\d{10}$/.test(mobile);return <Frame eyebrow="DELIVERY PARTNER SIGN UP" title="Become a Bowl delivery partner"><p>Create your partner profile. Verification and the onboarding fee come next.</p><label><UserRound/>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name"/></label><label><Phone/>Mobile<input value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="10-digit mobile number" inputMode="numeric"/></label><label>Vehicle type<select value={vehicle} onChange={e=>setVehicle(e.target.value)}><option>Bike</option><option>Scooter</option><option>Car</option></select></label><button className="auth-primary" disabled={!ok} onClick={()=>{localStorage.setItem('bowlDeliveryOnboarding',JSON.stringify({name:name.trim(),mobile,vehicle}));n('/delivery/verification')}}>Continue to verification</button><p className="auth-switch-text">Already a partner? <Link to="/delivery/signin">Sign in</Link></p></Frame>}

export function DeliverySignInPage(){const n=useNavigate();const[mobile,setMobile]=useState('');return <Frame eyebrow="DELIVERY PARTNER SIGN IN" title="Welcome back, partner"><p>Use your registered mobile number to access the delivery dashboard.</p><label><Phone/>Mobile<input value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,'').slice(0,10))} placeholder="10-digit mobile number" inputMode="numeric"/></label><button className="auth-primary" disabled={!/^\d{10}$/.test(mobile)} onClick={()=>n('/delivery/dashboard')}>Send OTP</button><p className="auth-switch-text">New partner? <Link to="/delivery/signup">Create a partner account</Link></p></Frame>}

export function DeliveryVerificationPage(){const n=useNavigate();const[data,setData]=useState(()=>JSON.parse(localStorage.getItem('bowlDeliveryOnboarding')||'{}'));const[docs,setDocs]=useState(false);return <Frame eyebrow="PARTNER VERIFICATION" title="Verify your partner profile"><p>Review your identity and driving documents before the one-time onboarding fee.</p><div className="auth-summary"><span>Partner <b>{data.name||'New partner'}</b></span><span>Vehicle <b>{data.vehicle||'Bike'}</b></span><span>Mobile <b>{data.mobile||'Not entered'}</b></span></div><label className="auth-check"><input type="checkbox" checked={docs} onChange={e=>setDocs(e.target.checked)}/> I have submitted valid identity and driving documents</label><button className="auth-primary" disabled={!docs} onClick={()=>{const next={...data,documentsVerified:true};localStorage.setItem('bowlDeliveryOnboarding',JSON.stringify(next));setData(next);n('/delivery/onboarding-fee')}}>Continue to fee</button></Frame>}

export function DeliveryFeePage(){const n=useNavigate();const[data,setData]=useState(()=>JSON.parse(localStorage.getItem('bowlDeliveryOnboarding')||'{}'));const[paid,setPaid]=useState(false);return <Frame eyebrow="ONBOARDING FEE" title="Complete partner onboarding"><div className="fee-card"><CreditCard/><div><strong>₹499</strong><span>One-time onboarding verification fee</span></div></div><p>Payment is simulated for this frontend prototype. Production will connect a secure payment gateway.</p><button className="auth-social" onClick={()=>setPaid(true)}>{paid?'✓ Fee marked paid':'Pay ₹499'}</button><button className="auth-primary" disabled={!paid} onClick={()=>{const next={...data,feeStatus:'PAID'};localStorage.setItem('bowlDeliveryOnboarding',JSON.stringify(next));registerDeliveryPartner(next);n('/delivery/application-submitted')}}>Submit application</button></Frame>}

export function DeliveryApplicationSubmittedPage(){return <Frame eyebrow="APPLICATION SUBMITTED" title="Verification in progress"><ShieldCheck className="auth-success"/><p>Your delivery partner application has been submitted. Admin verification is required before production access.</p><div className="auth-summary"><span>Documents <b>Submitted</b></span><span>Onboarding fee <b>Paid ₹499</b></span><span>Status <b>Pending admin review</b></span></div><Link className="auth-primary" to="/delivery/dashboard">Go to delivery preview</Link></Frame>}
